package cs3500.pa04.model.playerboards;

import cs3500.pa04.model.Coordinate;
import cs3500.pa04.model.Ship;
import cs3500.pa04.model.boardvalues.BoardValue;
import java.util.List;

/**
 * Represents a player's board in the game.
 */
public interface PlayerBoard {

  /**
   * Updates the user board to show the ship type for ships that have not been hit based on the list
   * of user ships.
   */
  void updateBoardValue();

  /**
   * Sets up the player board with the given list of ships and update the board to show the ships.
   *
   * @param ships the ships the player has on their board
   */
  void setup(List<? extends Ship> ships);

  /**
   * Given the list of shots the opponent has fired on this player board, reports which shots hit a
   * ship on this board. Updates the user's list of ships and user board based on the damage.
   *
   * @param opponentShotsOnBoard the opponent's shots on this player's board
   * @return a filtered list of the given shots that contain all locations of shots that hit a ship
   *     on this board
   */
  List<Coordinate> reportDamage(List<Coordinate> opponentShotsOnBoard);

  /**
   * Reports what shots in the player's previous volley successfully hit the opponent's ship.
   * Updates the opponent's board to show hits and misses.
   *
   * @param shotsThatHitOpponentShips the shots that hit opponent ships
   */
  void successfulHits(List<Coordinate> shotsThatHitOpponentShips);

  /**
   * Gets the opponent's board from this board's point of view.
   *
   * @return the board value [ ] [ ] representing the opponent's board
   */
  BoardValue[][] getOpponentBoardGrid();

  /**
   * Gets the user's board from this board's point of view.
   *
   * @return the board value [ ] [ ] representing the user's board
   */
  BoardValue[][] getUserBoardGrid();

  /**
   * Determines how many of the user's ships are not sunk.
   *
   * @return the int representing the number of ships a float
   */
  int shipsAfloat();

  /**
   * Determines how many shots the user is allowed to take. If the number of empty spots on the
   * opponent board is less than the number of ships a float, then the smaller number is used.
   *
   * @return the int representing the number of allowed shots
   */
  int shotsAllowed();

  /**
   * Updates the list of recent shots with new shots.
   *
   * @param shots the shots that could be added to the recent shots
   */
  void addShots(List<Coordinate> shots);

  /**
   * Updates the previous shots to be the recent shots taken, and clears the list of previous shots.
   * The shots taken is then the contents of the previous shots since they have been "taken."
   *
   * @return the list of shots taken
   */
  List<Coordinate> takeShots();

  /**
   * Determines if a given obj and this player board are equal based on their boards.
   *
   * @param obj the object this player board is being compared to
   * @return whether the given object and this player board are equal
   */
  @Override
  boolean equals(Object obj);

  /**
   * Returns the hashCode for this player board that's used for bucketing in Hash implementations.
   *
   * @return hash generated by the hashing algorithm
   */
  @Override
  int hashCode();
}
